import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import AuthProvider from "@/components/provider/auth-provider";
import { MainPage } from "@/components/custom/main-page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Streak",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <main>
            <MainPage>{children}</MainPage>
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
